### ISSUE TITLE
ERROR: Bad destination address

### ISSUE THREAD

**Issue by fischy667** [jsloan117/docker-openvpn-client#160] opened 2023-11-03 23:03 UTC
I have a ovpn-file from my provider. With this file I can connect using your docker container with the tag v3.1.
But when I'm using the latest container or the tag v4.0 cannot connect and get the following error.

```
2023-11-03T22:39:41.012916076Z allowing outbound to fr.vpnunlimitedapp.com: on device eth0

2023-11-03T22:39:42.779244635Z ERROR: Bad destination address

2023-11-03T22:39:42.804232798Z s6-rc: warning: unable to start service init-openvpn: command exited 1
```

### Config v3.1
```
docker run --cap-add=NET_ADMIN -d --name OpenVPN --restart always\
  -e CREATE_TUN_DEVICE=true \
  -v /volume1/docker/OpenVPN/fr_openvpn.ovpn:/etc/openvpn/custom/default.ovpn \
  -e OPENVPN_USERNAME=... \
  -e OPENVPN_PASSWORD=... \
  -e OPENVPN_OPTS="--auth-nocache --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings --data-ciphers-fallback 'AES-256-CBC'  \
  -e LOCAL_NETWORK=192.168.1.0/24 \
  -e S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 \
  -p 1195:1194 --dns 1.1.1.1 --dns 1.0.0.1 \
  jsloan117/docker-openvpn-client:v3.1
```
### Config 4.0

```
  docker run --cap-add=NET_ADMIN -d --name OpenVPN --restart always\
  -e CREATE_TUN_DEVICE=true \
  -v /volume1/docker/OpenVPN/:/etc/openvpn/custom \
  -e OPENVPN_CONFIG='fr_openvpn' \
  -e OPENVPN_USERNAME=... \
  -e OPENVPN_PASSWORD=... \
  -e LOCAL_NETWORK=192.168.1.0/24 \
  -e UFW_KILLSWITCH=true \
  -p 1195:1194 --dns 1.1.1.1 --dns 1.0.0.1 \
  jsloan117/docker-openvpn-client:v4.0
```

I checked the included OpenVPN Client version and in v3.1 OpenVPN 2.6.5 is used and in v4.0 it is OpenVPN 2.5.5. Is this intended?

**Comment by jsloan117** [comment] 2023-11-04 00:36
With version 4.x I switched back to Ubuntu (22.04) vs  Alpine Linux which is why the OpenVPN client version differences.

I doubt it but [this](https://github.com/haugene/vpn-configs-contrib/pull/249) *might* be related (or partly) so make sure you're pulling in the latest versions of your configs. I use a docker volume to hold mine, so if I want to update configs I need to delete and create said volume.

I feel the problem is related to UFW or specifically the `UFW_KILLSWITCH` setting which is by default set to `false`. I tested it again locally and doesn't seem to work like it did when I was testing a few months ago.

Either remove `UFW_KILLSWITCH` or set it to `false` and report back please.

**Comment by fischy667** [comment] 2023-11-04 00:52
You were right. I removed UFW_KILLSWITCH and now it works again. Thank you.

**Comment by jsloan117** [comment] 2023-11-04 01:16
Thanks for letting me know, I'll close this out for now.

**Closed** 2023-11-04 01:16 UTC
